21 rails preprocess datasets on upload
COSC481W-2024Fall/MLite pull request #32
Opened 2024-10-29 17:46 UTC by Ali-Almadhagi

**Description**
This pull request covers the full implementation of dataset upload, automated analysis, and extraction of key information to enhance dataset management. It also includes front-end updates to display extracted details and support efficient data preview.

**Finished Tasks**

- Extracted key details upon upload, including file size, row count, column count, and file type.
- Implemented the computation of basic metrics for numeric columns, such as mean, min, and max.
- Stored extracted details and metrics in the database to allow easy access and management.
- Updated the frontend to display dataset details and metrics on the "Show Dataset" page.
- Listed all uploaded datasets with relevant details on the index page for easy browsing.

**Testing**

- Unit tests were added to verify that file uploads and data extraction work correctly.
- Verified that extracted metrics and details are correctly displayed on the index and show pages.
- All tests passed, ensuring smooth functionality.

2024-11-01 00:39 UTC, Mohammad4844 requested changes
everything looks good for the most part. just a few copy/paste changes left. after that I'll merge

2024-11-01 00:39 UTC, Mohammad4844 commented on mlite_rails_app/app/controllers/datasets_controller.rb
> +      "float"
change this regex to `values.all? { |v| v.match?(/\A-?(?:\d+|\.\d+|\d+\.\d+)\z/) }`. this will match all numbers, so if some of them are like: 0.1, 33, .4, all will work.

2024-11-01 00:39 UTC, Mohammad4844 commented on mlite_rails_app/app/controllers/datasets_controller.rb
> +  end
same thing here. change regex to `values.all? { |v| v.match?(/\A-?(?:\d+|\.\d+|\d+\.\d+)\z/) }` so it counts an edge case like `.4`

2024-11-01 00:39 UTC, Mohammad4844 commented on mlite_rails_app/app/views/datasets/_dataset.html.erb
> +  <% end %>
can u change this to be in the #show page instead, and not the partial? that way it wont overpopulated the #index page. just copy paste this into the right place in #show

2024-11-02 22:01 UTC, Mohammad4844 approved these changes
Everything looks good.

2024-11-02 22:01 UTC, merged

2024-12-02 14:38 UTC, sjiang1 commented
Grading:
Quality of Code: Good
Participation in Code Review: Good
Post-Review Changes: Good

Deduction: Minor (-2)
Reason: Some commit messages do not adhere to the required format specified in the lecture. Examples: 45aca5f, 41bf334, 1f87c76