Added S3 setup for secure production storage
COSC481W-2024Fall/MLite pull request #35
Opened 2024-10-30 08:15 UTC by zsabri91

Features:

- Set up S3 storage specifically for production to securely store datasets and models
- Implement access control policies and encryption for secure and reliable data handling
- Integrated S3 with the production server to enable seamless loading of datasets and models

Testing:

- Deploy to production environment
- Verify that the production server can upload, access, and load datasets/models from S3
- Confirm access control and encryption policies are enforced on S3
- Test multiple scenarios to ensure smooth, secure data retrieval in production

Issue: #23

2024-10-30 16:05 UTC, Mohammad4844 requested changes
most of it looks good and works as expected. just a few redundant files to get rid of.

2024-10-30 16:05 UTC, Mohammad4844 commented on mlite_rails_app/app/models/user.rb
> +
remove this

2024-10-30 16:05 UTC, Mohammad4844 commented on mlite_rails_app/config/environments/development.rb
> +  config.active_storage.service = :amazon
put :local

2024-10-30 16:05 UTC, Mohammad4844 commented on mlite_rails_app/config/storage.yml
> +
remove

2024-10-30 16:05 UTC, Mohammad4844 commented on mlite_rails_app/config/routes.rb
remove

2024-10-30 16:05 UTC, Mohammad4844 commented on mlite_rails_app/config/initializers/aws.rb
remove this too

2024-11-01 00:47 UTC, Mohammad4844 approved these changes

2024-11-01 00:47 UTC, merged

2024-12-02 14:57 UTC, sjiang1 commented
Grading Feedback:

Quality of Code: Good
Participation in Code Review: Good
Post-Review Changes: Good

Deduction: Minor (-2 points)
Reason: Some commit messages do not adhere to the required format specified in the lecture. Please ensure future commit messages align with the established guidelines.